blogs/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url
from mainapp.views import *
from user import views as user_views

urlpatterns = [
    path('', homepage, name='home'),
    path('admin/', admin.site.urls),
    path('new_articles/', new_articles),  # 最新文章
    path('add_article/', add_article),
    path('hot_articles/', hot_articles),  # 热门文章
    re_path(r'^category/(\w?)/$', article_category),
    url(r'^article/(\d+)/$', show_article),  # 文章具体内容
    re_path(r'^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$', archives),
    path('videos/<str:slug>/', listvideos, name='listvideos-url'),
    path('video/<str:link>/', video),
    path('video/<str:link>/<str:index>', video, name='video-url'),
    path('up/<str:link>/<str:index>', up),  # 视频上一集
    path('down/<str:link>/<str:index>', down),  # 视频下一集
    re_path(r'^kinds/(\d+)/$', kind, name='kind-url'),
    re_path(r'^select/(\d+)/(\d+)$', select),        # 视频选集
    path('search/', search_article),     # 搜索文章
    re_path(r'^blog/$', user_views.index),
    re_path(r'^article/edit/$', user_views.article_edit),
    re_path(r'^blog_article_content/(\d+)/$', user_views.blog_article_content),
    re_path(r'^contract/$', contract),
    re_path(r'^blog_article_kind/(\d+)/$',
            user_views.blog_article_kind, name='blog_article_kind_url'),
    re_path(r'^signin/$',user_views.signin),
    re_path(r'^signup/$',user_views.signup),
    re_path(r'^logout/$',user_views.user_logout),
    re_path(r'^captcha/',include('captcha.urls')),
    re_path(r'^my_blog/$',user_views.my_blog,name='my_blog-url'),
    re_path(r'^article/delete/(\d+)/$',user_views.delete_article),
    re_path(r'^article/edit/(\d+)/$',user_views.update_article),
]

user/models.py
from django.db import models
from django.db.models.base import ModelState
from django.db.models.fields import CharField, TextField
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Tag(models.Model):
    tagname = models.CharField(max_length=32)

    def __str__(self):
        return self.tagname


class Kind(models.Model):
    kindname = models.CharField(max_length=20)

    def __str__(self):
        return self.kindname


class Article(models.Model):
    CATEGORY_TYPE = (
        ('O', '原创'),
        ('R', '转载')
    )

    PERMISSION_TYPE = (
        ('public', '公开'),
        ('private', '私密'),
        ('fans', '仅粉丝可见')
    )

    author=models.ForeignKey('User',on_delete=models.CASCADE,verbose_name='作者')
    article_id = models.CharField(max_length=20, null=True)
    title = CharField(max_length=200)
    content = models.TextField()
    post_datetime = models.DateTimeField(auto_now_add=True)
    category = models.CharField(
        default='O', choices=CATEGORY_TYPE, max_length=1)
    permission = models.CharField(
        default='public', choices=PERMISSION_TYPE, max_length=8)
    tag = models.ForeignKey(to='Tag', on_delete=models.CASCADE)
    kind = models.ForeignKey(to='Kind', on_delete=models.CASCADE)
    read_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class User(AbstractUser):
    nickname=models.CharField(max_length=32,verbose_name='昵称')

    def __str__(self):
        return self.username

templates/article.html
{% extends 'base.html' %} {% load markdown_deux_tags %} {% block title %}
{{article.title }} - 灰灰博客 {% endblock %}
{% block content %}
<h2 class="mb-5">{{ article.title }}</h2>
<p style="font-family: '微软雅黑'; font-size: 12pt; letter-spacing: 2pt">
  {{ article.content|markdown }}
</p>
{% endblock %}

templates/article_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}新增文章{% endblock %}
{% block header %}新增文章{% endblock %}
{% block content %}
<form action="." method="POST">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary bt-2 btn-block btn-lg">发布</button>
</form>

{% endblock %}





<!-- <form action="." method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="author">作者</label>
        <input type="text" class="form-control" id="author" name="author" placeholder="输入作者名称">
    </div>
    <div class="form-group">
        <label for="title">标题</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="输入文章标题">
    </div>
    <div class="form-group">
        <label for="content_">内容</label>
        <textarea name="content_" id="content_" class="form-control"></textarea>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="o" name="category" value="O">
        <label for="o" class="form-check-label">原创</label>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="r" name="category" value="R">
        <label for="r" class="form-check-label">转载</label>
    </div>
    <br>
    <div class="form-group">
        <label for="kind">分类专栏</label>
        <select name="kind" id="kind" class="form-control">
            {% for kind in kinds %}
            <option value="{{ kind.pk }}">{{ kind }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="tag">文章标签</label>
        <select name="tag" id="tag" class="form-control">
            {% for tag in tags %}
            <option value="{{ tag.pk }}">{{ tag }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="public" name="permission" value="public">
        <label for="public" class="form-check-label">公开</label>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="private" name="permission" value="private">
        <label for="private" class="form-check-label">秘密</label>
    </div>
    <div class="form-check form-check-inline">
        <input type="radio" class="form-check-input" id="fans" name="permission" value="fans">
        <label for="fans" class="form-check-label">仅粉丝可见</label>
    </div>
    <br>
    <button type="submit" class="btn btn-primary mt-2 btn-block btn-lg">发布</button>
</form> -->

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        window.onload = function () {
            var url = "http://127.0.0.1:8000";
            var request = new XMLHttpRequest();
            request.open("GET", url);
            request.send(null);
        }
        function back() {
            history.go("-1");
        }
    </script>
</head>
<body>
    <div class="container-fluid">
        <!-- {% include 'header.html' %} -->
        {% include 'navbar.html' %}
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        ssblog官方博客
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item"><a href="/">首页</a></li>
                            <li class="list-group-item"><a href="/hot_articles/">热门文章</a></li>
                            <li class="list-group-item"><a href="#kind">分类专栏</a></li>
                            <li class="list-group-item"><a href="#">最新评论</a></li>
                            <li class="list-group-item"><a href="/new_articles">最新文章</a></li>
                            <li class="list-group-item"><a href="/add_article">添加文章</a></li>
                            <li class="list-group-item"><a href="/contract">私信</a></li>
                        </ul>
                    </div>
                </div>
                {% block hotArticle %}{% endblock %}
                {% block archives %}{% endblock %}
                {% block kinds %}{% endblock %}
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        {% block header %}{% endblock %}
                    </div>
                    <div class="card-body">
                        {% block content %}{% endblock %}
                    </div>
                    <div class="card-footer">
                        {% include 'footer.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/base_my_blog.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        window.addEventListener("load", function () {
            var xmlhttp;
            if (window.XMLHttpRequest) {
                xmlhttp = new XMLHttpRequest();
            } else {
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.addEventListener("readystatechange", function () {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                    pass
                }
            })
            xmlhttp.open("GET", "http://127.0.0.1:8000/my_blog/", true);
            xmlhttp.send(null);
        })
    </script>
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>

</html>

templates/blog_article_content.html
{% extends 'blog.html' %}
{% load markdown_deux_tags %}
{% block title %}{{ article.author }}的文章{% endblock %}
{% block content %}
<div class="card">
    <div class="card-body">
        <h2 class="mb-5">{{ article.title }}</h2>
        <p style="font-family: '微软雅黑'; font-size: 12pt; letter-spacing: 2pt">
            {{ article.content|markdown }}
        </p>
    </div>
</div>
{% endblock %}

templates/blog_article_kind.html
{% extends 'blog.html' %}
{% block title %}{{kind}}{% endblock %}
{% block content %}
{% for article in articles %}
<div class="card mt-2 mb-2 border-warning">
    <div class="card-body">
        <h4 class="card-title">
            <span class="badge badge-danger">
                {{ article.get_category_display }}
            </span>
            <a href="/blog_article_content/{{ article.id }}">{{ article.title }}</a>
        </h4>
        <h6 class="card-subtitle mb-2 text-muted">
            作者：{{ article.author }}
        </h6>
        <p class="card-text">
            {{ article.content|truncatechars:20 }}...
        </p>
        <small>
            {{ article.post_datetime }}
            阅读数：{{ article.read_count }}
        </small>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/contract.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}发送私信{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2 btn-block btn-lg">发布</button>
</form>
{% endblock %}

templates/footer.html
{% block footer %}
    {% if now %}
        <p>现在时刻：{{ now }}</p>
    {% else %}
        <p>本文内容取自网络，如有侵权请来信通知下架...</p>
    {% endif %}
{% endblock %}

templates/header.html
{% load static %}
<div class="card bg-info mt-3 mb-3">
    <div class="card-body">
        <h3 class="float-left">
            <img src="{% static 'images/bg.gif' %}" alt="" width="70" height="70">
            灰灰博客
        </h3>
        <div class="float-right btn-group" role="group">
            <a href="/category/O" class="btn btn-secondary">原创</a>
            <a href="/category/R" class="btn btn-secondary">转载</a>
        </div>
    </div>
</div>

templates/index.html
{% extends 'base.html' %}
{% block title %}欢迎光临灰灰博客{% endblock %}
{% block header %}博客{% endblock %}
{% block hotArticle %}
<div class="card mt-2">
    <div class="card-header">
        热门文章
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for hot_article in hot_articles %}
            <li class="list-group-item">
                <span class="badge badge-danger">
                    {{ hot_article.get_category_display }}
                </span>
                <a href="/article/{{ hot_article.article_id }}">
                    {{ hot_article.title }}
                </a>
                <small>
                    阅读数：{{ hot_article.read_count }}
                </small>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block archives %}
<div class="card mt-2">
    <div class="card-header">
        最新文章
    </div>
    <div class="card-body">
        <div class="card-title">
            2021
        </div>
        <div class="row">
            {% for archive in archives %}
            <div class="col-4 mt-2">
                <a href="/archives/2021/{{ archive.0 }}" role="button"
                    class="btn btn-outline-secondary btn-small btn-block">
                    {{ archive.0 }}月
                    <span class="badge badge-success">{{ archive.1 }}篇</span>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block kinds %}
<div class="card mt-2" id="kind">
    <div class="card-header">
        分类专栏
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for item in article_kind_list %}
            <li class="list-group-item">
                <a href="{% url 'kind-url' forloop.counter %}">{{ item.0 }}</a>
                <span>{{ item.1 }}篇</span>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

{% block content %}
{% for i in articles %}
<div class="card mb-2 mt-2 border-warning">
    <div class="card-body">
        <h4 class="card-title">
            <span class="badge badge-danger">
                {{ i.get_category_display }}
            </span>
            <a href="/article/{{ i.article_id }}">{{i.title}}</a>
        </h4>
        <p class="card-text">
            {{ i.content|truncatechars:20 }}...
        </p>
        <small>
            {{ i.post_datetime }}
            阅读数：{{ i.read_count }}
        </small>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/my_blog.html
{% extends 'base_my_blog.html' %}
{% block title %}
博客
{% endblock %}
{% block content %}
<div class="container-fluid">
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% for article in articles %}
    <div class="card mt-2 mb-2 border-warning">
        <div class="card-body">
            <h4 class="card-title">
                <span class="badge badge-danger">
                    {{ article.get_category_display }}
                </span>
                <a href="/blog_article_content/{{article.id}}">{{ article.title }}</a>
            </h4>
            <p class="card-text">
                {{ article.content|truncatechars:20 }}
            </p>
            <small>
                {{ article.post_datetime }}
                阅读数：{{ article.read_count }}
            </small>
        </div>
        <div class="card-footer">
            <a href="/article/edit/{{ article.id }}" class="btn btn-primary mt-2">修改文章</a>
            <a href="/article/delete/{{ article.id }}" class="btn btn-danger mt-2">删除文章</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/new_articles.html
{% extends 'base.html' %}
{% block title %}
    最新文章
{% endblock %}
{% block header %}最新文章列表{% endblock %}
{% block content %}
    {% for new_article in new_articles %}
        <div class="card mt-2 mb-2 border-warning">
            <div class="card-body">
                <h4 class="card-title">
                    <span class="badge badge-danger">
                        {{ new_article.get_category_display }}
                    </span>
                    <a href="/article/{{ new_article.article_id }}">
                        {{ new_article.title }}
                    </a>
                </h4>
                <p class="card-text">
                    {{ new_article.content|truncatechars:20 }}...
                </p>
                <small>
                    {{ new_article.post_datetime }}
                    阅读数：{{ new_article.read_count }}
                </small>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
登录
{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}
    <form action="." method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-2 btn-lg">登录</button>
    </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
注册
{% endblock %}
{% block content %}
    {% if message %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endif %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-2 btn-lg">注册</button>
    </form>
{% endblock %}